---
version: "2.1"

volumes:
  postgresql_data:

services:
  db:
    image: postgres
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:62001:5432"

  medialog:
    build:
      context: "rails/"
    ports:
      - "127.0.0.1:62080:3000"
