version: "3"

volumes:
  postgresql:
  medialog:
  home:

services:

  medialog:
    build:
      context: "rails/"
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - "postgresql:/var/lib/pgsql/9.4/"
      - "medialog:/opt/medialog/"
      - "home:/home/medialog/"