development:
  adapter: postgresql
  encoding: unicode
  database: medialog_dev
  username: medialog
  password: medialog
  host: db
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: medialog_dev
  username: medialog
  password: medialog
  host: db
  port: 5432
